### PR TITLE
Bugfix in openQCD routines: r_stop was excluded instead of being the …

### PR DESCRIPTION
**Pull request by s-kuberski**
…last element

### CODE REVIEW

**Comment by s-kuberski** [comment]
Wait, that might have been too fast.

**Comment by s-kuberski** [comment]
It is really hard to track all the special cases. We definitely need some test routines for these input routines. I did not appropriately handle the case, where r_stop was equal to the last config. This is now also taken care of and I hope, that everything is fine.

**Comment by fjosw** [comment]
Thanks for spotting the bug. I agree that tests would be really reassuring. I am a little afraid of bloating up the repo with many test files but I guess we can find a solution to this.

**Comment by s-kuberski** [comment]
I'll create some small tests based on a short 4^4 chain. The RWFs have a negligible size. The gradient flow measurements however would need about 200K (for .gfms.dat - Zeuthen flow and .ms.dat - Wilson flow for t0).

**Pull request merged**
