### PR TITLE
Feature/input 2.0

### PR DESCRIPTION
**Pull request by jkuhl-uni**
A few bug fixes, testing of input methods as well as changing one parameter for the sfcf-input.
rwms input also changed.

### CODE REVIEW

**Review by s-kuberski — CHANGES_REQUESTED** [review]
The changes to `openQCD.py` are not compatible with the ones that were made in 77c0f5aadcacf1df4f65dda96762f797db6d5075. By now, we deal correctly with idl based on the data in the file such that the keyword idl_offsets is not needed anymore.

**Comment by jkuhl-uni** [comment]
Yes, that is true, the changes made here can be discarded

**Comment by fjosw** [comment]
Thanks for the bug fixes and the tests. I would suggest to add explicit `assert` statements to the tests which check that you indeed obtain the expected result.

Please also make to resolve any conflicts with Simon's changes so I can merge the pull request.

**Comment by fjosw** [comment]
I had a brief look at the tests. I believe the test functions have to start with `test` to be recognized by pytest. To get the tests working I had to add `tests/` to the beginning of all relative paths.

**Comment by jkuhl-uni** [comment]
Concerning the tests: I already worked on that yesterday, I just forgot to push to github.

I'm currently wroking on resolving conflicts.

**Comment by jkuhl-uni** [comment]
Merge conflicts should be resolved now. (and thee tests are also ready)

**Comment by fjosw** [comment]
You committed redundant files in the folder /data/sfcf_test which are now part of the git history. I will clean that up but please be careful in the future. (This is why I recommended the pytest `tmpdir` fixture which automatically cleans up).

**Pull request merged**
