### PR TITLE
hash method for Obs objects

### PR DESCRIPTION
**Pull request by fjosw**
This is my first attempt at a reproducible hash function for `Obs` objects. I construct a tuple out of the value, the deltas, the errsq of the covobs and the names and hash that. All numerical values are cast to single precision via numpy which hopefully takes care of any rounding errors that can occur.

### CODE REVIEW

**Comment by s-kuberski** [comment]
The use of single precision is very smart, I had the fear that our non-binary I/O would lead to problems in this application. At some point, we could include the hash in the JSON file if the computation is fast, compared to the I/O.

**Comment by fjosw** [comment]
Thanks. I tried to write the hash method in such a way that two objects that compare as equal also have the same hash but I am sure that one can construct special cases for which this is not the case. Do you think it is worth adding the hash method to the library?

The slight problem with writing the hash to a file is that this hash can probably not be easily reproduced in other programming languages. We could still add it to files as an optional check. Or we might consider a more portable hash method.

**Comment by fjosw** [comment]
I followed up on my earlier comment and changed the hashing algorithm to md5 which should be portable and reproducible.

**Comment by s-kuberski** [comment]
The change to md5 makes it definitely easier to compute the hash in other implementations, as well. I am not sure if it is necessary to add this to the I/O. In my opinion it crucially depends on the overhead that is introduced when writing and reading a large number of observables.

**Pull request merged**
